### PR TITLE
Collisions

### PR DESCRIPTION
**Pull request by jbovensa**
Handle downsizing of Mario from collisions with Koopa/Pirana/Fireball.
Allow Mario to hit a Pirana only when it is out of its pipe.

### CODE REVIEW

**Comment by jazzyjester** [comment]
@jbovensa Hey, thanks for the PR, I can't currently test it since I don't have Visual Studio installed but I'll try to understand only from the code.
Thanks.

**Comment by jbovensa** [comment]
Thanks :-)
You're an excellent host

**Review by jazzyjester — APPROVED** [review]
LGTM, I think that need to create big refactor since all the collision code is in one file and it's really hard to maintain....

**Comment by jbovensa** [comment]
OK.
Meanwhile do you intend to merge the pull request?

**Comment by jazzyjester** [comment]
done, thanks.

**Pull request merged**
